// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rkjneuscjvddodkzgfmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJram5ldXNjanZkZG9ka3pnZm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwODA0MDIsImV4cCI6MjA4MzY1NjQwMn0.Hd75V3P2uepzYBmAyZeZAKG0aJdeIRpySL_L5G6-nJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);